name: Unzip project
on: workflow_dispatch
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -o lotto535_final_with_firebase.zip -d .
          rm lotto535_final_with_firebase.zip
          # di chuyển file từ thư mục con ra ngoài
          if [ -d "lotto535_app_final" ]; then
            cp -r lotto535_app_final/* . || true
            cp -r lotto535_app_final/.github . || true
            rm -rf lotto535_app_final
          fi
          if [ -d "lotto535_final_with_firebase" ]; then
            cp -r lotto535_final_with_firebase/* . || true
            rm -rf lotto535_final_with_firebase
          fi
          ls -la
      - run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add .
          git commit -m "auto unzip" || echo "no change"
          git push
